name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ktlint:
    name: Run ktlint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run ktlint
      run: ./gradlew ktlint

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run tests
      run: ./gradlew testNokey
